console.log("Hello World")
console.log("Hola el mundo")
console.log("Hallo")
console.log("Ciao")
console.log("Bounjur")
console.log("Ola")
console.log("Nin Hao")
console.log("Guten Tag")
console.log("Konnichiwa ")
console.log("Anyeonghaseyo")